on: 
  schedule:
    - cron: "0 0 * * *"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to extend
    steps:
      - name: Helloaction
        id: helloaction
        uses: future-death/helloaction@main
